- name: set static hostnames in /etc/hosts
  lineinfile: dest=/etc/hosts line={{ item }}
  with_items:
    - "{{ vm_nics[0].ip }} {{ hostname }}"
    - "{{ hostvars['rhevh1'].vm_nics[1].ip }} {{ hostvars['rhevh1'].hostname }}"
    - "{{ hostvars['rhevh2'].vm_nics[1].ip }} {{ hostvars['rhevh2'].hostname }}"

- name: copy the answerfile over
  template: src=templates/answers_withdwh_rhv{{ current_lifecycle_env.rhv_version }}.j2 dest=/root/answers

- name: configure rhev via answerfile
  command: engine-setup --config-append=/root/answers  creates=/etc/ovirt-engine-setup.conf.d/20-setup-ovirt-post.conf
  register: engine_setup

- name: create .rhevmshellrc (for RHEV 3.6)
  template: src=rhevmshellrc.j2 dest=/root/.rhevmshellrc mode=0600
  when: current_lifecycle_env.rhv_version == 3

- name: create .ovirtshellrc (for RHEV 4.x)
  template: src=ovirtshellrc.j2 dest=/root/.ovirtshellrc mode=0600
  when: current_lifecycle_env.rhv_version == 4

# - pause: minutes=2
#   when: engine_setup|changed

- name: wait for rhev web ui to become available
  wait_for: host={{ vm_nics[0].ip }} port=443 timeout=600
