- block:
    - include: prepare_host.yml
      tags: ['layer1','layer1-host']
    - include: configure_bridge.yml
      tags: ['layer1','layer1-bridge']
    - include: define_libvirt_storage_pools.yml
      tags: ['layer1','layer1-libvirt-storage']
    - include: define_libvirt_networks.yml
      tags: ['layer1','layer1-libvirt-networks']
    - include: copy_installation_sources.yml
      tags: ['layer1','layer1-sources']
    - include: prepare_kickstart_folder.yml
      tags: ['layer1','layer1-kickstart-folder']
    - include: enable_nfs.yml
      tags: ['layer1','layer1-nfs']
    - include: configure_ntp.yml
      tags: ['layer1','layer1-ntp']
    - include: configure_iptables.yml
      tags: ['layer1','layer1-iptables']
    - include: prepare_user_with_kvm_access.yml
    # export the binary dir via NFS
    - include: roles/common/tasks/prepare_nfs_export.yml
      vars:
        items:
          - path: "{{ layer1_binary_dir }}"
        export_params: "(ro)"
      tags: ['layer1','layer1-nfs-binary']
  when: mode=='create'

- block:
    #- include: remove_user_with_kvm_access.yml
    #- include: remove_iptables.yml
    - include: destroy_libvirt_networks.yml
    - include: remove_bridge.yml
  when: mode=='destroy'
