---
name: test-rhel7
mem: 2048
vcpu: 2
disk:
  path: test-rhel7.qcow2
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000
nic:
  - ip: 192.168.100.22
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.22
    dev: eth1
    network: admin
    default_route: false
#hostname is now set in group_vars/all.yml
#hostname: test-rhel7.example.com
#root_password is now set in config/hailstorm_config.yml
#root_password: redhat01
ansible_host: 192.168.103.22
