////
 style_guide.adoc

-------------------------------------------------------------------------------
   Copyright 2016 Kevin Morey <kevin@redhat.com>

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------
////

= Style Guide
The following is a list of suggested style guidelines to follow when contributing to this project.

* <<General Guidelines>>
* <<Alerts>>
* <<Automate>>
* <<Buttons>>
* <<Control>>
* <<Dialogs>>
* <<Reports>>

== General Guidelines

* Be as descriptive as possible. Nothing worse then looking at something and not knowing what it is or what it is suppose to do.
* Use snake_case when possible.
* Start names with the product if you are writing for a provider product.
* If the dialog is non-product pecific then prefix the name with the primary object type (vm, host, service, etc...).

NOTE: I.e. vcenter_mount_cdrom, openstack_create_load_balancer, rhev_evacuate_vms or vm_stop_my_vm, host_ssh_and_do_something, etc...

<<top>>

== Alerts

* Name the alerts something meaningful.

<<top>>

== Automate

* Automate domains are not case-sensitive however we have found that standardizing on a particular style improves usability
** Namespace - Use CamelCase (i.e. FooNameSpace || FooMIQTestNamespace)
** Class - Use CamelCase (i.e. FooClass || FooMIQTestClass)
** Instance - Use snake_case (foo_instance)
** Method - Use snake_case (foo_method)
*** There is more to come regarding methods

<<top>>

== Buttons

* For dialogs associated with buttons try and keep the name the same as the request name. This way it is easy to tell which button belongs to a dialog and request.
* For dialogs associated with service catalog items review the <<General Guidelines>>.

<<top>>

== Control

* Name the policy/profiles something meaningful. For instance, compliance_vm_shell_shock_check tells us that this is a compliance policy for vms and checks for the shell shock vulnerability

<<top>>

== Dialogs

* For dialogs associated with buttons please try and keep the name the same as the request name. This way it is easy to tell which button belongs to a dialog and request.
* For dialogs associated with service catalog items review the <<General Guidelines>>.

<<top>>

== Reports

* Start the report name with what table the report is based on. I.e. vm, real-time performance, cluster, etc...
* Altough it is not mandatory it is good practice to create a dashboard widget to with the report.

<<top>>
