---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: vmware
    inherits: 
    description: 
  fields:
  - vendor:
      value: "'${/#vm.vendor.downcase}' == 'vmware'"
  - Step1:
      value: "/Infrastructure/VM/Operations/StateMachines/Methods/initialize_rightsizing_tags"
  - Step2:
      value: "/Infrastructure/VM/Operations/StateMachines/Methods/check_vm_tags"
  - Step3:
      value: "/Infrastructure/VM/Operations/StateMachines/Methods/check_powered_off"
  - Step4:
      value: "/Infrastructure/VM/Operations/StateMachines/Methods/right_size_vm"
