---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - set_fact:
        rhsm_username: "{{ rhsm_username }}"
        rhsm_password: "{{ rhsm_password }}"
      tags:
        - always
    - debug: var=vm_nics
      tags:
        - always
    # - debug: msg={{ vm_nics }}
    #   tags:
    #     - always

  vars_prompt:
    - name: "rhsm_username"
      prompt: "what is your Red Hat Subscription Manager username?"
      default: "wrichter"
      private: no
    - name: "rhsm_password"
      prompt: "what is your Red Hat Subscription Manager password?"

- hosts: layer1
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer1', 'rhosp', 'rhev', 'ose3', 'dnat' ]
  roles:
    - role: layer1
      tags: [ 'layer1' ]
      mode: create
    - role: layer1_dnat
      tags: [ 'layer1', 'dnat' ]
      mode: create
    - role: layer1_rhosp
      tags: [ 'rhosp', layer1 ]
      mode: create
    - role: layer1_rhev
      tags: [ 'rhev', layer1 ]
      mode: create
    - role: layer1_openshift
      tags: [ 'ose3', layer1 ]
      mode: create
    #- role: layer1_vms
    #  tags: [ 'layer2','satellite','vm' ]
    #  mode: create
    #  group: satellite
    #- role: layer1_vms
    #  tags: [ 'layer2','rhosp', 'vm' ]
    #  mode: create
    #  group: rhosp-all
    # - role: layer1_vms
    #   tags: [ 'layer2','rhev', 'vm' ]
    #   mode: create
    #   group: rhev


#### SATELLITE ####

- hosts: satellite
  remote_user: root
  gather_facts: false
  #pre_tasks:
  #  - setup:
  #    tags: [ 'layer2','satellite' ]
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'satellite', 'vm' ], mode: create }
  #  - { role: layer2_dnat, tags: [ 'layer2', 'satellite', 'dnat' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2','satellite', 'rhel' ], mode: create }
    - { role: layer2_satellite, tags: [ 'layer2','satellite' ], mode: create }

# - hosts: test-rhel
#   remote_user: root
#   gather_facts: false
#   roles:
#     - { role: layer2_vms, tags: [ 'layer2', 'satellite', 'vm', 'test-rhel' ], mode: create }
#     - { role: layer2_rhel, tags: [ 'layer2', 'satellite', 'rhel', 'test-rhel' ], mode: create }

#### IPA ####

- hosts: ipa
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'ipa', 'vm' ], mode: create }
#    - { role: layer2_dnat, tags: [ 'layer2', 'ipa', 'dnat' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'ipa', 'rhel' ], mode: create }
    - { role: layer2_ipa, tags: [ 'layer2', 'ipa' ], mode: create }

#### SATELLITE (again) ####

- hosts: satellite
  remote_user: root
  gather_facts: false
  #pre_tasks:
  #  - setup:
  #    tags: [ 'layer2','satellite' ]
  roles:
   - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'satellite', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
   - { role: layer2_tdagent, tags: [ 'layer2', 'satellite', 'tdagent' ], mode: create }


# - hosts: test-rhel
#   remote_user: root
#   gather_facts: false
#   roles:
#     - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'satellite', 'test-rhel', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    #- { role: layer2_tdagent, tags: [ 'layer2', 'satellite', 'test-rhel', 'tdagent' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }


#### Infrastructure (DNS, SMTP/IMAP) ####

- hosts: infrastructure
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'infrastructure', 'vm' ], mode: create }
#    - { role: layer2_dnat, tags: [ 'layer2', 'infrastructure', 'dnat' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'infrastructure', 'rhel' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'infrastructure', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_infrastructure, tags: [ 'layer2', 'infrastructure' ], mode: create }

#### RHEV ####

- hosts: rhev
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhev', 'vm' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'rhev', 'rhel' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'rhev', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }

- hosts: rhevm
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2', 'rhev' ]
  roles:
#    - { role: layer2_dnat, tags: [ 'layer2', 'rhev', 'dnat' ], mode: create }
    - { role: layer2_rhevm_engine, tags: [ 'layer2', 'rhev', 'rhevm' ], mode: create }
    - { role: layer2_rhevdhw_cfme, tags: [ 'layer2', 'rhev', 'rhevm', 'cfme-rhevdwh' ], mode: create }
    - { role: layer2_tdagent, tags: [ 'layer2', 'rhev', 'tdagent' ], mode: create }

- hosts: rhevh
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2', 'rhev' ]
  roles:
    - { role: layer2_rhevh, tags: [ 'layer2', 'rhev', 'rhevh' ], mode: create }

- hosts: rhevm
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2', 'rhev','rhevm', 'rhevm-ldap','rhevm-storage' ]
  roles:
    - { role: layer2_rhevm_storage, tags: [ 'layer2', 'rhev', 'rhevm','rhevm-storage' ], mode: create }
    - { role: layer2_rhevm_ldap, tags: [ 'layer2', 'rhev', 'rhevm', 'rhevm-ldap' ], mode: create }


- hosts: satellite
  remote_user: root
  gather_facts: false
  pre_tasks:
    - setup:
      tags: [ 'layer2', 'satellite-rhev' ]
  roles:
    - { role: layer2_satellite_rhev, tags: [ 'layer2', 'satellite-rhev', 'satellite', 'rhev' ], mode: create }

#### OpenShift 3 ####

- hosts: ose3
  remote_user: root
  gather_facts: false
  # pre_tasks:
  #   - setup:
  #     tags: [ 'layer2', 'rhev' ]
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'ose3', 'vm' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'ose3', 'rhel' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'ose3', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layerX_openshift_all, tags: [ 'layer2', 'ose3', 'ose3-installprep' ], mode: create }

- hosts: ose3-common
  remote_user: root
  gather_facts: false
  roles:
    - { role: layerX_openshift_node, tags: [ 'layer2', 'ose3', 'ose3-node' ], mode: create }

- hosts: ose3-installer
  remote_user: root
  gather_facts: false
  roles:
    - { role: layerX_openshift_installer, tags: [ 'layer2', 'ose3', 'ose3-install' ], mode: create }
    - { role: layerX_openshift_cfme_enablement, tags: [layer2, 'ose3', 'cfme-ose3-provider'], mode: create }
    - { role: layerX_openshift_devops_tools, tags: ['ose3-devops'], mode: create }
    - { role: layerX_openshift_demo_monster, tags: ['ose3-demo'], mode: create }

#### OPENSTACK ####

- hosts: rhosp-all
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhosp', 'vm' ], mode: create }

- hosts: rhosp-director
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_rhel, tags: [ 'layer2', 'rhosp', 'rhel'], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'rhosp', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhosp_director, tags: ['layer2', 'rhosp', 'undercloud' ], mode: create }
    - { role: layer2_rhosp_overcloud, tags: ['layer2', 'rhosp', 'overcloud'], mode: create }
#    - { role: layer2_rhosp_gather_node_uuids, tags: ['layer2', 'rhosp', 'overcloud'], mode: create }


#### CLOUDFORMS ####

- hosts: cloudforms
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_cloudforms_rhev, tags: [ 'layer3', 'cf' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer3', 'cf', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer3_cloudforms_config, tags: [ 'layer3', 'cf', 'cfme-config' ], mode: create }
    - { role: layer3_cloudforms_osp, tags: [ 'layer3', 'cf', 'cfme-osp-provider' ], mode: create }
    - { role: layer3_cloudforms_openshift, tags: [ 'layer3', 'cf', 'cfme-ose3-provider' ], mode: create }
    - { role: layer3_cloudforms_content, tags: [ 'layer3', 'cf', 'cfme-content' ], mode: create, content_location: "../CloudForms-Internals" }


- hosts: efk
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'efk', 'vm' ], mode: create }
    - { role: layer2_rhel, tags: [ 'layer2', 'efk', 'rhel'], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'efk', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_efk_rhosp_optools, tags: [ 'layer2', 'efk', 'efk-install'], mode: create }
